Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 100
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false